=== ghaffar35/Challenge_3/cv.dtd
<!DOCTYPE CV [
<!ELEMENT page (section*)>
<!ELEMENT section (identite?, contact?, custom?, competence?, formation?, experience?, hobbie?)>
<!ELEMENT identite (prenom, nom, naissance, site?)>
	<!ELEMENT prenom (#PCDATA)>
	<!ELEMENT nom (#PCDATA)>
	<!ELEMENT naissance (#PCDATA)>
	<!ELEMENT site (#PCDATA)>
<!ELEMENT contact (adresse, tel, mail)>
	<!ELEMENT adresse (numero, rue, cp, ville, pays?)>
		<!ELEMENT numero (#PCDATA)>
		<!ELEMENT rue (#PCDATA)>
		<!ELEMENT cp (#PCDATA)>
		<!ELEMENT ville (#PCDATA)>
		<!ELEMENT pays (#PCDATA)>
	<!ELEMENT tel (#PCDATA)>
	<!ELEMENT mail (#PCDATA)>
<!ELEMENT custom (#PCDATA)>
<!ELEMENT competence (#PCDATA)>
<!ELEMENT formation (intitule, date, ecole, descriptif)>
	<!ELEMENT intitule (#PCDATA)>
	<!ELEMENT date (#PCDATA)>
	<!ELEMENT ecole (#PCDATA)>
	<!ELEMENT descriptif (#PCDATA)>
<!ELEMENT experience (intitule, datedebut, datefin, lieux, descriptif)>
	<!ELEMENT datedebut (#PCDATA)>
	<!ELEMENT datefin (#PCDATA)>
	<!ELEMENT lieux (#PCDATA)>
<!ELEMENT hobbie (#PCDATA)>
<!ELEMENT image (#PCDATA)>
]>

=== ghaffar35/Challenge_3/index.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!DOCTYPE CV SYSTEM "cv.dtd">
	<?xml-stylesheet href="style.css" type="text/css" ?>

<page>
	<section>
		<identite>
			<prenom>hbsckjcdjkvn</prenom>
			<nom>ffiurdfioguerifov</nom>
			<naissance>25/12/65</naissance>
		</identite>
	</section>

	<section>
		<contact> 
			<adresse>
				<rue><rue>
				<cp> </cp>
			 
			</adresse>
		</contact>
	</section>
</page>
